-- ===========================================================================
-- Qlink :: wallet analytics events
-- ---------------------------------------------------------------------------
-- Adds support for tracking the wallet-connect funnel in page_events.
-- Drops and re-creates the event type check constraint to allow:
--   wallet_button_click
--   wallet_connect_click
--   wallet_connected
-- ===========================================================================

-- 1. Add new columns for wallet tracking (can be null for non-wallet events)
ALTER TABLE public.page_events ADD COLUMN IF NOT EXISTS network text;
ALTER TABLE public.page_events ADD COLUMN IF NOT EXISTS wallet_type text;

-- 2. Update the check constraint to allow new event types.
-- The name generated by Supabase/Postgres is typically page_events_type_check.
-- We drop it if it exists and add a new one.
ALTER TABLE public.page_events DROP CONSTRAINT IF EXISTS page_events_type_check;
ALTER TABLE public.page_events ADD CONSTRAINT page_events_type_check 
  CHECK (type IN (
    'page_view',
    'section_view',
    'package_open',
    'checkout_start',
    'wallet_button_click',
    'wallet_connect_click',
    'wallet_connected'
  ));
